### ISSUE TITLE
cartpole_example Segmentation fault

### ISSUE THREAD

**Issue by EPVelasco** [ACDSLab/MPPI-Generic#4]
Hi, I have compiled everything but I can't run the example `./cartpole_example`. 
I have this error: Segmentation fault (core dumped)

However, the double_integrator_example and double_integrator_CORL2020 examples run. 

![image](https://github.com/user-attachments/assets/f01628e4-0e82-4f72-aee8-4a7e1719799c)

My CUDA version is:
![image](https://github.com/user-attachments/assets/91c9a5b8-792e-44b4-bb4b-4eaf8addf68c)

**Comment by bosky2001** [comment]
@EPVelasco I compiled instead as a cu file instead cpp and that fixed it for me! I don't really know why or how that worked , but I don't get the seg fault error anymore.

**Comment by bogidude** [comment]
Changing it to a .cu file worked because then all the header files for dynamics, cost functions, etc. will include their CUDA method definitions into the compilation of the executable. However, we would like to support the capability for someone to choose to compile all of the CUDA-specific code they need (an MPPI controller for cartpole for example) into a shared library and then link to it from a cpp-based executable. This seems to be currently broken so I shall set it to be a .cu file for now while we investigate this further.

**Comment by bogidude** [comment]
Fixed in #3 and has been merged into `main` with `.cu` workaround for now.
